### ISSUE TITLE
你好,多表查询的DEMO可以简单说明下如何显示吗?

### ISSUE THREAD

**Issue by 119992278** [cuo9958/sequelize-api#2]
你好,多表查询的DEMO可以简单说明下如何显示吗?

**Comment by cuo9958** [comment]
返回的数据格式是1对多得形式，可以循环获取最低的数据列表显示数据列表，也可以转换一次变成真正的一个列表，然后渲染这个列表

**Comment by 119992278** [comment]
您提供的DEMO里,例子可以表达清楚些..具体不知道在哪里调用看效果

**Comment by cuo9958** [comment]
连接一个你自己的数据库,然后执行对应的js文件.
控制台会输出执行的sql语句和返回的数据.

不同的表代表不同使用方式,需要取消对应的注释
